services:
  ingestion:
    build:
      context: .
      dockerfile: pipeline/ingestion/Dockerfile
    environment:
      EIA_API_KEY: ${EIA_API_KEY}
      PYTHONPATH: /app
      SNOWFLAKE_ACCOUNT: ${SNOWFLAKE_ACCOUNT}
      SNOWFLAKE_USER: ${SNOWFLAKE_USER}
      SNOWFLAKE_PASSWORD: ${SNOWFLAKE_PASSWORD}
      SNOWFLAKE_ROLE: ${SNOWFLAKE_ROLE}
      SNOWFLAKE_WAREHOUSE: ${SNOWFLAKE_WAREHOUSE}
      SNOWFLAKE_DATABASE: ${SNOWFLAKE_DATABASE}
      SNOWFLAKE_SCHEMA: ${SNOWFLAKE_SCHEMA}
    volumes:
      - ./pipeline:/app/pipeline

  airflow:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    entrypoint: ["/bin/bash", "-lc"]
    command:
      - >
        airflow db migrate &&
        airflow users create
        --role Admin
        --username admin
        --password admin
        --firstname Admin
        --lastname User
        --email admin@example.com ||
        airflow users reset-password
        --username admin
        --password admin;
        exec airflow standalone
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
      AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW__CORE__LOAD_EXAMPLES}
      PYTHONPATH: /opt/airflow
      _AIRFLOW_WWW_USER_CREATE: ${AIRFLOW_WWW_USER_CREATE}
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_WWW_USER_USERNAME}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_WWW_USER_PASSWORD}
      EIA_API_KEY: ${EIA_API_KEY}
      SNOWFLAKE_ACCOUNT: ${SNOWFLAKE_ACCOUNT}
      SNOWFLAKE_USER: ${SNOWFLAKE_USER}
      SNOWFLAKE_PASSWORD: ${SNOWFLAKE_PASSWORD}
      SNOWFLAKE_ROLE: ${SNOWFLAKE_ROLE}
      SNOWFLAKE_WAREHOUSE: ${SNOWFLAKE_WAREHOUSE}
      SNOWFLAKE_DATABASE: ${SNOWFLAKE_DATABASE}
      SNOWFLAKE_SCHEMA: ${SNOWFLAKE_SCHEMA}
    ports:
      - "28080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./pipeline:/opt/airflow/pipeline
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/health > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 20

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      PYTHONPATH: /app
      SNOWFLAKE_ACCOUNT: ${SNOWFLAKE_ACCOUNT}
      SNOWFLAKE_USER: ${SNOWFLAKE_USER}
      SNOWFLAKE_PASSWORD: ${SNOWFLAKE_PASSWORD}
      SNOWFLAKE_ROLE: ${SNOWFLAKE_ROLE}
      SNOWFLAKE_WAREHOUSE: ${SNOWFLAKE_WAREHOUSE}
      SNOWFLAKE_DATABASE: ${SNOWFLAKE_DATABASE}
      SNOWFLAKE_APP_SCHEMA: ${SNOWFLAKE_APP_SCHEMA}
    ports:
      - "28501:8501"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8501/_stcore/health', timeout=5)\""]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - ./app:/app
