[pytest]
testpaths =
    ingestion/tests
    airflow/tests
    app/tests
    admin_app/tests
    spark/tests
filterwarnings =
    error
    ignore::pytest.PytestUnraisableExceptionWarning
xfail_strict = true
